### ISSUE TITLE
Version Update

### ISSUE THREAD

**Issue by MCMicS** [Sobesednik/dist-exiftool#7]
It is possible to update the versions? I've created the changes but the merge is missin. If you want, you can grant me access for the repos and I will maintain it

**Comment by MCMicS** [comment]
@z-vr Can you merge or give write access?
@Sobesednik: It is possible to get write access

**Comment by MCMicS** [comment]
Hi @Sobesednik, @z-vr, @neojski   
Is there any possiblity to add me as additional contributer?
I will maintain the versions

**Comment by neojski** [comment]
I don't own this repo, sorry. I can't help here.

**Comment by MCMicS** [comment]
thanks for answer. But you have commit rigths?

**Comment by neojski** [comment]
I don't think so. I might have contributed to this tool in the past but I
was never closely involved in it.

**Comment by MCMicS** [comment]
thanks for answering.
@Sobesednik, @z-vr: Is there anyway to grant write access to keep this project alive?

**Comment by ndtreviv** [comment]
@z-vr  Привет, мы можем решить эту проблему, пожалуйста?

**Comment by MCMicS** [comment]
There is another project: https://github.com/photostructure/exiftool-vendored.js

**Comment by ndtreviv** [comment]
> There is another project: https://github.com/photostructure/exiftool-vendored.js

Yeah but it's up to 6 times slower at extracting metadata than this one (https://github.com/photostructure/exiftool-vendored.js/issues/61), 60x on Windows!

**Comment by mceachen** [comment]
> Yeah but it's up to 6 times slower at extracting metadata

Sorry @ndtreviv , you're reading that wrong: [exiftool-vendored.js](https://github.com/photostructure/exiftool-vendored.js) is the one that's (much) faster, especially on higher thread-count CPUs. If you have reproducible benchmarks that indicate otherwise, I'll happily look into them. I posted more details to the issue you referenced explaining how there is such a large performance gap.

**Comment by MCMicS** [comment]
publish own version of this package
