### ISSUE TITLE
Question: how does install work?

### ISSUE THREAD

**Issue by ndtreviv** [Sobesednik/dist-exiftool#9]
I want to wrap up `dist-exiftool` and `node-exiftool` as part of an electron application. I will be doing builds for both windows and macOS using `electron-builder`. Will each platform distribution include the correct binary for exiftool, or does `dist-exiftool` literally install the right binary on `yarn add ...` ?

**Comment by MCMicS** [comment]
dist-install use the right binary. I use it in an electron app too

**Comment by ndtreviv** [comment]
Yep, I can confirm this now as well.
